# -*- coding: utf-8 -*-
"""institutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WN9dIRsVsyoVnwA5xdGOWUYjLkeCTPtR
"""

import pandas as pd
import json

df = pd.read_csv('MERGED2019_20_PP.csv')

universityData = df[["INSTNM", "LATITUDE", "LONGITUDE", "UGDS"]]
universityData = universityData.rename(columns = {"INSTNM":'Institution', "LATITUDE":'Latitude', 
                                 "LONGITUDE":'Longitude', "UGDS":'UndergradStudentCount'})

universityDataJSON = universityData.to_json(orient = 'records')
parsed = json.loads(universityDataJSON)
with open('universityData.json', 'w') as json_file:
 json.dump(universityDataJSON, json_file)