# -*- coding: utf-8 -*-
"""synthetic500.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9KiOXqqRKYYMA2hTzIo6z3LHQSI82g-
"""

import pandas as pd
import numpy as np
from pandas.core.common import random_state

df = pd.read_csv("merged_data.tsv", sep="\t", header=0)

np.random.seed(509)
listoflists = []
for col in df.columns:
  lst = np.random.choice(df[col],500)
  listoflists.append(list(lst))

random500 = pd.DataFrame(list(zip(listoflists[1], listoflists[2], listoflists[3], listoflists[4], 
                      listoflists[5], listoflists[6], listoflists[7], listoflists[8], listoflists[9], 
                      listoflists[10], listoflists[11], listoflists[12], listoflists[13], listoflists[14], 
                      listoflists[15], listoflists[16], listoflists[17], listoflists[18], listoflists[19], listoflists[20], 
                      listoflists[21], listoflists[22], listoflists[23], listoflists[24], listoflists[25], listoflists[26], 
                      listoflists[27], listoflists[28], listoflists[29], listoflists[30], listoflists[31], listoflists[32], 
                      listoflists[33], listoflists[34])), columns = df.columns[1:35])

realAndFakePapers = pd.concat([random500,df])
new = realAndFakePapers.drop(['Unnamed: 0'], axis=1)

new.to_csv('realAndFakePapers.csv')